### ISSUE TITLE
zcat: can't stat ... 

### ISSUE THREAD

**Issue by liviuspenter** [landau-lab/Gotcha#6]
When running `FastqSplit()` on MacOS I get the error `zcat: can't stat ...`. 

Would you be able to change the `zcat` command to `gunzip -c` in FastqSplit()? That would fix this problem under MacOS.
https://github.com/landau-lab/Gotcha/blob/2436287e4ef8fcac952ecc2d5cd90b0828131207/R/FastqSplit.R#L22

Thank you,

livius

**Comment by fizzo13** [comment]
Thanks for the suggestion, @Theob0t can you take a look at this?

**Comment by fizzo13** [comment]
@Theob0t can you take a look at this potential improvement?

**Comment by Theob0t** [comment]
Hi, it has been fixed. Thanks!
