### ISSUE TITLE
barcode matching very slow

### ISSUE THREAD

**Issue by liviuspenter** [landau-lab/Gotcha#7]
Hello,

the barcode matching part in `MutationCalling()` from 737K-cratac-v1.txt or singlecell.csv is a real bottleneck - it takes hours and hours. 

Have you thought about using just the filtered_peak_bc_matrix/barcodes.tsv as whitelist? This would narrow the search space considerably from 500k+ to 5-10k barcodes. 

The other thought I have is whether it doesn't make sense to just create a dictionary of all possible mismatched cell barcodes plus their whitelisted counterparts and look up each entry from R2 in that dictionary. 

For example if your whitelist cell barcode is AAA and you allow 1 mismatch, you would create the following dictionary:
AAA AAA
CAA AAA
ACA AAA
AAC AAA
TAA AAA
ATA AAA
AAT AAA
GAA AAA
AGA AAA
AAG AAA

Now you can just look up the whitelisted barcode from column 2 for each R2 read by using column 1 as index. If you don't find anything, you discard the read. 

livius

**Comment by Theob0t** [comment]
Hi,

Our development version of the Gotcha package is using a single `barcodes.file.path` argument for the whitelist. 

Using this version you can input the `filtered_peak_bc_matrix/barcodes.tsv` file from CellRanger and it will reduce computational time.

To install the development version you can run:
`devtools::install_github(repo = "landau-lab/Gotcha",ref = "development", force = T)`
