### ISSUE TITLE
lsf compatibility

### ISSUE THREAD

**Issue by scZfish** [landau-lab/Gotcha#9]
Our cluster uses LSF so the BatchMutationCalling function will not work as in the provided example. Are there options for implementing parallelization using an LSF job manager?

**Comment by Theob0t** [comment]
Hi, 

We are planning to included LSF support in future development.

The `slurm_apply()` call in `BatchMutationCalling.R` need to be replaced using the R package _bsub_ [https://jokergoo.github.io/bsub_vignettes/bsub_intro.html] to submit the `MutationCalling` jobs to an LSF cluster.
